#Sharing dependency versions between projects
# 多工程之间的依赖版本管理

[versions]
#groovy = "3.0.5"
#checkstyle = "8.37"
arrowVersion = "8.0.0"


[libraries]
#groovy-core = { module = "org.codehaus.groovy:groovy", version.ref = "groovy" }
#groovy-json = { module = "org.codehaus.groovy:groovy-json", version.ref = "groovy" }
#groovy-nio = { module = "org.codehaus.groovy:groovy-nio", version.ref = "groovy" }
#commons-lang3 = { group = "org.apache.commons", name = "commons-lang3", version = { strictly = "[3.8, 4.0[", prefer = "3.9" } }

arrowVector                 = { module = "org.apache.arrow:arrow-vector", version.ref = "arrowVersion" }
arrowMemoryCore             = { module = 'org.apache.arrow:arrow-memory-core', version.ref = 'arrowVersion' }
arrowMemoryNetty            = { module = 'org.apache.arrow:arrow-memory-netty', version.ref = 'arrowVersion' }
arrowFlight                 = { module = 'org.apache.arrow:arrow-flight', version.ref = 'arrowVersion' }
arrowPlasma                 = { module = 'org.apache.arrow:arrow-plasma', version.ref = 'arrowVersion' }

[bundles]
#groovy = ["groovy-core", "groovy-json", "groovy-nio"]

[plugins]
#jmh = { id = "me.champeau.jmh", version = "0.6.5" }



